name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    env:
      DOCKER_CONTAINER_REGISTRY: groffegithubactions.azurecr.io
      NOME_IMAGEM: $DOCKER_CONTAINER_REGISTRY/apiconsultaacoesmongo0
      PATH_PROJETO: ./APIConsultaAcoesMongo

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login no Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ env.DOCKER_CONTAINER_REGISTRY }}
      
    - name: Build e Push no Azure Container Registry
      run: |
        cd ${{ env.PATH_PROJETO }}
        docker build . --file Dockerfile --tag ${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag ${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER ${{ env.NOME_IMAGEM }}:latest
        docker push ${{ env.NOME_IMAGEM }}
